use_frameworks!

platform :ios, '10.0'

target 'JKBeeHivewMJRefresh_Example' do
  pod 'JKBeeHivewMJRefresh', :path => '../'
  pod 'MJRefresh' , '~>3.0'
  pod "BeeHive",'~>1.6'
  target 'JKBeeHivewMJRefresh_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
