use_frameworks!

platform :ios, '8.0'

target 'JKBeeHivewMJRefresh_Example' do
  pod 'JKBeeHivewMJRefresh', :path => '../'

  target 'JKBeeHivewMJRefresh_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
